Add missed kotlin flag
line/armeria pull request #3689
Opened 2021-07-10 11:41 UTC by heowc

Motivation:

Kotlin related modules are missing `kotlin` flags.

Modifications:

- Add `kotlin` flag

Result:

- Enables working with Kotlin in the examples module.

2021-07-10 13:41 UTC, ikhoon approved these changes
Nice catch! @heowc

2021-07-12 01:20 UTC, minwoox requested changes
Thanks!

2021-07-12 01:21 UTC, minwoox approved these changes

2021-07-12 03:32 UTC, trustin approved these changes
Thanks, @heowc !

2021-07-12 03:32 UTC, merged