Fix DocService to accept non JSON requests
line/armeria pull request #5381
Opened 2024-01-13 11:47 UTC by heowc

Motivation:

1) Trying to use json pretty even though it's a string that can't use json pretty, like json-lines.
2) When copying as a curl command, it uses an array of characters to insert duplicate semantically identical headers.

Modifications:

1) Trying to use json pretty even though it's a string that can't use json pretty, like json-lines.
  - Fix some mime types to ignore pretty
2) When copying as a curl command, it uses an array of characters to insert duplicate semantically identical headers.
  - Change to `Headers` instead of string array

Result:

- Closes #5218

2024-04-01 12:34 UTC, minwoox approved these changes
Apologize for the late review. 😓 
Looks good, thanks!

2024-04-01 12:34 UTC, minwoox commented on docs-client/src/lib/transports/transport.ts
> +const ignoringPrettyMimeTypes: string[] = ['x-ndjson', 'json-seq'];
How about `nonJsonPrettifyMimeTypes`?

2024-04-01 12:34 UTC, minwoox commented on docs-client/src/lib/transports/transport.ts
> +  private ignorePretty(applicationType: string) {
How about `shouldPrettify`?

2024-04-01 12:41 UTC, minwoox requested changes

2024-04-01 12:41 UTC, minwoox commented on docs-client/src/lib/transports/transport.ts
> +        if (this.ignorePretty(applicationType)) {
We should add this logic for the request body not for the response body. 😓 
https://github.com/line/armeria/blob/3af883e675201e0c119360bb786ac98b69db7246/docs-client/src/containers/MethodPage/DebugPage.tsx#L190

2024-04-04 06:45 UTC, jrhee17 commented
Pushed a small commit which

- Adds a `jsonLines` method for easier testing to `AnnotatedDocServiceTest`
- Extracts `validateJsonObject` so that multiple components can use it
- Check if `content-type` is overridden in `transport.ts` - If it is, then skip the json check

Let me know if changes don't make sense

2024-04-04 07:59 UTC, minwoox approved these changes
Thanks a lot! 😄

2024-04-04 08:22 UTC, jrhee17 approved these changes
👍 👍 👍

2024-04-08 06:09 UTC, ikhoon approved these changes
Thanks @heowc! 🙇‍♂️🙇‍♂️

2024-04-08 06:10 UTC, merged

2024-04-09 07:45 UTC, heowc commented
Oops..!

I took a wrong approach, thank you for correcting me 🙇